/* Generated By:JavaCC: Do not edit this line. ProjLangASTParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ProjLangASTParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SEMI = 5;
  /** RegularExpression Id. */
  int EQ = 6;
  /** RegularExpression Id. */
  int ASSIGNMENT = 7;
  /** RegularExpression Id. */
  int LT = 8;
  /** RegularExpression Id. */
  int LPAR = 9;
  /** RegularExpression Id. */
  int RPAR = 10;
  /** RegularExpression Id. */
  int ADDOP = 11;
  /** RegularExpression Id. */
  int MULOP = 12;
  /** RegularExpression Id. */
  int NOT = 13;
  /** RegularExpression Id. */
  int IF = 14;
  /** RegularExpression Id. */
  int THEN = 15;
  /** RegularExpression Id. */
  int ELSE = 16;
  /** RegularExpression Id. */
  int WHILE = 17;
  /** RegularExpression Id. */
  int FOR = 18;
  /** RegularExpression Id. */
  int DO = 19;
  /** RegularExpression Id. */
  int LET = 20;
  /** RegularExpression Id. */
  int FUN = 21;
  /** RegularExpression Id. */
  int VAL = 22;
  /** RegularExpression Id. */
  int IN = 23;
  /** RegularExpression Id. */
  int END = 24;
  /** RegularExpression Id. */
  int TRUE = 25;
  /** RegularExpression Id. */
  int FALSE = 26;
  /** RegularExpression Id. */
  int LCURL = 27;
  /** RegularExpression Id. */
  int RCURL = 28;
  /** RegularExpression Id. */
  int NUM = 29;
  /** RegularExpression Id. */
  int ID = 30;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\";\"",
    "\"=\"",
    "\":=\"",
    "\"<\"",
    "\"(\"",
    "\")\"",
    "<ADDOP>",
    "<MULOP>",
    "\"!\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"while\"",
    "\"for\"",
    "\"do\"",
    "\"let\"",
    "\"fun\"",
    "\"val\"",
    "\"in\"",
    "\"end\"",
    "\"true\"",
    "\"false\"",
    "\"{\"",
    "\"}\"",
    "<NUM>",
    "<ID>",
  };

}
